[Feature][47890]Initial API
awesome-academy/MovieDB_58 pull request #6
Opened 2022-04-06 02:06 UTC by 2fng

## [Pull request title]
[Feature][47890]Initial API
### [Redmine link]
https://edu-redmine.sun-asterisk.vn/issues/47890
#### Screenshots (nếu có)

2022-04-06 02:27 UTC, namtn-2711 requested changes

2022-04-06 02:27 UTC, namtn-2711 commented on NetflixClone/NetflixClone/Networking/APICaller.swift
> +        let url = URL(string: "\(Constants.baseURL)/trending/\(media)/\(timeWindow)?api_key=\(Constants.APIKey)")
Quản lý url tại 1 component khác

2022-04-06 02:27 UTC, namtn-2711 commented on NetflixClone/NetflixClone/Models/TvDetail.swift
> +struct TvDetail: Codable {
Tách ra các file riêng

2022-04-06 02:27 UTC, namtn-2711 commented on NetflixClone/NetflixClone/Networking/APICaller.swift
> +    static let shared = APICaller()
tổ chức thành singleton

2022-04-06 02:27 UTC, namtn-2711 commented on NetflixClone/NetflixClone/Networking/APICaller.swift
> +}
viết 1 hàm call api chung. Call cái nào thì viết vào repository

2022-04-06 02:27 UTC, namtn-2711 commented on NetflixClone/NetflixClone/Controllers/HomeTableViewController.swift
> +        APICaller.shared.getTvDetail(id: 1668)
ko call như này

2022-04-06 04:35 UTC, daolq-2712 commented on NetflixClone/NetflixClone/Networking/APICaller.swift
> +    static let APIKey = "4c8686d0d2ee37d6f04bd0eca7ca6efb"
Không push APIKey lên như này e
Nên dấu trong file .Plist & add .gitIgnore không push lên

2022-04-06 04:39 UTC, 2fng commented on NetflixClone/NetflixClone/Networking/APICaller.swift
> +    static let APIKey = "4c8686d0d2ee37d6f04bd0eca7ca6efb"
Vâng ạ

2022-04-06 10:36 UTC, dongtg-1485 reviewed
- Những phần liên quan request API em nên tách ra một `class` riêng để quản lý nó, ví dụ `APIRepository`.
- Các trường hợp error như request API cẩn phải được hiển thị lỗi bằng popup.
- Các hàm request API cần phải có callback trả về để handle request.
- Check lại xem các request em đang gọi trên `MainThread` hay `BackGround`, nếu gọi trên `MainThread` thì UI của em sẽ bị lock cho tới khi request được thực hiện xong.

2022-04-06 10:36 UTC, dongtg-1485 commented on NetflixClone/NetflixClone/Info.plist
> +	</dict>
@2fng 
Phần này sao lại phải mở `AppTransportSecurity` vậy em?

2022-04-06 10:36 UTC, dongtg-1485 commented on NetflixClone/NetflixClone/Models/ListedItem.swift
> +    let id: Int?
Riêng id bắt buộc không được phép thiếu nên mình không để là `Optional` nhé.

2022-04-06 10:36 UTC, dongtg-1485 commented on NetflixClone/NetflixClone/Models/ListedItem.swift
> +    let id: Int?
Update lại tương tự với các entity khác.

2022-04-06 10:36 UTC, dongtg-1485 commented on NetflixClone/NetflixClone/Networking/ManageURL.swift
> +        return URL(string: "https://api.themoviedb.org/3/\(endpoint)")!
Không force unwrap.

2022-04-06 10:36 UTC, dongtg-1485 commented on NetflixClone/NetflixClone/Networking/ManageURL.swift
> +    case genre(apiKey: String, mediaType: MediaType)
API key nên để vào 1 base equest, không nên để mỗi request đều truyền param vào như thế này.

2022-04-06 10:36 UTC, dongtg-1485 commented on NetflixClone/NetflixClone/Networking/APICaller.swift
> +}
Cho vào một file riêng để quản lý các domain, url web,...

2022-04-06 10:41 UTC, 2fng commented on NetflixClone/NetflixClone/Info.plist
> +	</dict>
E bị lỗi tương tự ở thread này và làm theo cách được recommend phía dưới ạ

https://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http

2022-04-06 10:49 UTC, namtn-2711 commented on NetflixClone/NetflixClone/Controllers/HomeTableViewController.swift
> +            print("Fetching is done!")
tách ra function riêng

2022-04-06 10:49 UTC, namtn-2711 commented on NetflixClone/NetflixClone/Controllers/HomeTableViewController.swift
> +    public func getAPIKey() -> String {
sao lại public? thế này vc nào cx cần get lại api à e

2022-04-07 01:35 UTC, daolq-2712 reviewed
Pls check my comments!

2022-04-07 01:35 UTC, daolq-2712 commented on NetflixClone/NetflixClone/Controllers/HomeTableViewController.swift
> +            self?.getMovieDetail(id: 634649)
``id: 634649`` hard code?

2022-04-07 01:35 UTC, daolq-2712 commented on NetflixClone/NetflixClone/Controllers/HomeTableViewController.swift
> +            self?.getTvDetail(id: 1399)
như trên

2022-04-07 01:35 UTC, daolq-2712 commented on NetflixClone/NetflixClone/Controllers/HomeTableViewController.swift
> +    func getTvDetail(id: Int) {
get Detail ở màn này để làm gì e?

2022-04-07 01:40 UTC, thuannv-2723 commented on NetflixClone/NetflixClone/Controllers/HomeTableViewController.swift
> +    func popUPError(error: Error) {
```suggestion
    func popupError(error: Error) {
```

2022-04-07 02:00 UTC, ghost commented on NetflixClone/NetflixClone/Networking/ManageURL.swift
> +        if let url = URL(string: "https://api.themoviedb.org/3/\(endpoint)?api_key=\(Constants.apiKey)") {
```suggestion
        if let url = URL(string: "\(Constants.baseURL)/\(endpoint)?api_key=\(Constants.apiKey)") {
```

2022-04-07 06:16 UTC, phonglh-2668 approved these changes

2022-04-07 06:22 UTC, namtn-2711 commented on NetflixClone/NetflixClone/Networking/APIRepository.swift
> +// Get functions
xoá cmt nếu ko cần thiết

2022-04-07 06:22 UTC, namtn-2711 commented on NetflixClone/NetflixClone/Networking/APIRepository.swift
> +protocol Repository {
```suggestion
protocol APIRepositoryType {
```

2022-04-07 06:30 UTC, merged