[Task][47893]Handle Event
awesome-academy/MovieDB_58 pull request #8
Opened 2022-04-08 10:43 UTC by 2fng

## [Pull request title]
[Task][47893]Handle Event
### [Redmine link]
https://edu-redmine.sun-asterisk.vn/issues/47893?issue_count=30&issue_position=22&next_issue_id=47892&prev_issue_id=47894
#### Screenshots (nếu có)

2022-04-08 12:44 UTC, dongtg-1485 reviewed
Về cấu trúc folder project nên nhóm theo từng màn hình, tức là mỗi folder chứa các thành phần của màn hình đó như view, viewModel, useCase, controller, ....

2022-04-08 12:44 UTC, dongtg-1485 commented on NetflixClone/NetflixClone/Controllers/CategoryViewController.swift
> +        closeButton.layer.cornerRadius = 20
tách riêng ra func `configViews()`

2022-04-08 12:44 UTC, dongtg-1485 commented on NetflixClone/NetflixClone/Controllers/CategoryViewController.swift
> +        cell.textLabel?.textAlignment = .center
- Config UI cell thì bỏ vào trong cell.
- Set data thì tạo hẳn một func để set dữ liệu như `func setContentForCell()` hoặc `func binding(_ model: Model)`

2022-04-08 12:44 UTC, dongtg-1485 commented on NetflixClone/NetflixClone/Controllers/CategoryViewController.swift
> +        print("Item at row \(indexPath)")
Remove trash code.

2022-04-08 12:44 UTC, dongtg-1485 commented on NetflixClone/NetflixClone/Controllers/DetailTableViewController.swift
> +        print(itemId, isMovie)
Tách ra func config riêng và remove trash code.

2022-04-08 12:44 UTC, dongtg-1485 commented on NetflixClone/NetflixClone/Controllers/HomeTableViewController.swift
> +        let notiName = Notification.Name(rawValue: "com.Turacle.itemTapped")
Khai báo `notiName` trong `extension Notification.Name`

2022-04-08 12:44 UTC, dongtg-1485 commented on NetflixClone/NetflixClone/Controllers/HomeTableViewController.swift
> +        print("Search button tapped")
Remove

2022-04-08 12:44 UTC, dongtg-1485 commented on NetflixClone/NetflixClone/Controllers/HomeTableViewController.swift
> +        }
Em phải dùng một property để quản lý state, không bao giờ đc quản lý state bằng view nhé

2022-04-08 12:44 UTC, dongtg-1485 commented on NetflixClone/NetflixClone/Controllers/HomeTableViewController.swift
> +        }
Tương tự, không được quản lý state bằng view

2022-04-08 12:44 UTC, dongtg-1485 commented on NetflixClone/NetflixClone/Controllers/HomeTableViewController.swift
> +        }
Không quản lý state bằng view

2022-04-08 12:44 UTC, dongtg-1485 commented on NetflixClone/NetflixClone/Controllers/SearchTableViewController.swift
> +        view.backgroundColor = .red
tách func config

2022-04-08 12:44 UTC, dongtg-1485 commented on NetflixClone/NetflixClone/Controllers/SeeAllViewController.swift
> +
không config view và set content trực tiếp tại delegate

2022-04-08 12:44 UTC, dongtg-1485 commented on NetflixClone/NetflixClone/Controllers/SeeAllViewController.swift
> +        let height = view.frame.size.height/5
```suggestion
        let width = view.frame.size.width / 3.2
        let height = view.frame.size.height / 5
```

2022-04-12 00:48 UTC, daolq-2712 requested changes
Pls check my comments!

2022-04-12 00:48 UTC, daolq-2712 commented on NetflixClone/NetflixClone/Scenes/Category/CategoryTableViewCell.swift
> +
remove blank line!

2022-04-12 00:48 UTC, daolq-2712 commented on NetflixClone/NetflixClone/Scenes/Detail/DetailTableViewController.swift
> +
remove blank line!

2022-04-12 00:48 UTC, daolq-2712 commented on NetflixClone/NetflixClone/Scenes/Detail/DetailTableViewController.swift
> +    init(id: Int, isMovie: Bool) {
_init_ should be the first method of a class

2022-04-12 00:48 UTC, daolq-2712 commented on NetflixClone/NetflixClone/Scenes/Search/SearchTableViewController.swift
> +
remove blank line!

2022-04-12 00:48 UTC, daolq-2712 commented on NetflixClone/NetflixClone/Scenes/SeeAll/SeeAllCollectionViewCell.swift
> +        self.layer.cornerRadius = 5
with 1 line of code, we do not create a new method.

2022-04-12 00:48 UTC, daolq-2712 commented on NetflixClone/NetflixClone/Scenes/SeeAll/SeeAllViewController.swift
> +        viewTitle?.text = "Trending"
add above this line

> // TODO update later

2022-04-12 00:48 UTC, daolq-2712 commented on NetflixClone/NetflixClone/Scenes/SeeAll/SeeAllViewController.swift
> +        return 20
add above this line

> // TODO update later

2022-04-12 00:48 UTC, daolq-2712 commented on NetflixClone/NetflixClone/Scenes/SeeAll/SeeAllViewController.swift
> +
remove blank line!

2022-04-12 01:24 UTC, daolq-2712 reviewed
Pls check my comments!

2022-04-12 01:24 UTC, daolq-2712 commented on NetflixClone/NetflixClone/Scenes/Category/CategoryTableViewCell.swift
> +        // Initialization code
remove this comment or put this comment on above method ``configCellUI()``

2022-04-12 01:24 UTC, daolq-2712 commented on NetflixClone/NetflixClone/Scenes/Category/CategoryTableViewCell.swift
> +    override func setSelected(_ selected: Bool, animated: Bool) {
remove unused func

2022-04-12 01:24 UTC, daolq-2712 commented on NetflixClone/NetflixClone/Scenes/Category/CategoryTableViewCell.swift
> +    func configCellUI() {
if not call outside of class should define _private_

2022-04-12 01:24 UTC, daolq-2712 commented on NetflixClone/NetflixClone/Scenes/SeeAll/SeeAllViewController.swift
> +extension SeeAllViewController: UICollectionViewDelegate {
should remove if not used.
we only will implement it when used

2022-04-12 01:46 UTC, daolq-2712 approved these changes
LGTM!

2022-04-12 01:49 UTC, merged